sudo: required
services:
  - docker

jest:
  - "24.3.0"

before_install:
  - docker build -t caseylaw/docker-react -f Dockerfile.dev .

script:
  - docker run caseylaw/docker-react npm test -- --coverage